### ISSUE TITLE
RBAC for linkerd configuration

### ISSUE THREAD

**Issue by prasenforu** [linkerd/linkerd-examples#167] opened 2017-07-19 15:33 UTC
This will be good if we get configuration file  with & without RBAC for kubernetes

**Comment by klingerf** [comment] 2017-07-19 17:05
Closing this as a dupe of linkerd/linkerd#1347. An RBAC configuration is up for review in #165 -- please take a look there.

**Closed by klingerf** 2017-07-19 17:05 UTC
